### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films with a duration sup to a minimum
GET {{baseUrl}}/films?minimum-duration=140

### find a film with the right id

GET {{baseUrl}}/films/1

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title" : "Teeeesssttt",
    "duration": 250,
    "budget": 1000000000,
    "link": "www.test.be"
}

### Delete film by id
DELETE {{baseUrl}}/films/4

### Patch film identified by 2
PATCH {{baseUrl}}/films/2
Content-Type: application/json

{
  "title": "The Godfather",
  "duration": 175,
  "budget": 6000000,
  "link": "https://youtube.com/the-godfather"
}